# Generated by Django 6.0.2 on 2026-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'PIX')], max_length=20),
        ),
    ]
