# Generated by Django 6.0.2 on 2026-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(default=0, help_text='Quantidade em estoque'),
        ),
    ]
