# Generated by Django 6.0.2 on 2026-02-11 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_produto_quantidade_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combo', to='caixa.produto')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
            },
        ),
        migrations.CreateModel(
            name='ComboSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Escolha seu Lanche, Escolha sua Bebida', max_length=100)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição do slot')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='caixa.combo')),
            ],
            options={
                'verbose_name': 'Slot do Combo',
                'verbose_name_plural': 'Slots do Combo',
                'ordering': ['ordem'],
                'unique_together': {('combo', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='ComboSlotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_abate', models.DecimalField(decimal_places=3, help_text='Quantidade que será abatida do estoque (ex: 1.0, 0.5, 200.0)', max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caixa.produto')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='caixa.comboslot')),
            ],
            options={
                'verbose_name': 'Item do Slot',
                'verbose_name_plural': 'Itens do Slot',
                'unique_together': {('slot', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='PedidoComboEscolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_abatida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolhas_combo', to='caixa.itempedido')),
                ('produto_escolhido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caixa.produto')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caixa.comboslot')),
            ],
            options={
                'verbose_name': 'Escolha do Combo',
                'verbose_name_plural': 'Escolhas do Combo',
                'unique_together': {('item_pedido', 'slot')},
            },
        ),
    ]
