# Generated by Django 6.0.2 on 2026-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_combo_comboslot_comboslotitem_pedidocomboescolha'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comboslotitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comboslotitem',
            name='quantidade_abate',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Quantidade que será abatida do estoque (fixo em 1.0)', max_digits=10),
        ),
    ]
