# Generated by Django 6.0.2 on 2026-02-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_remove_comboslotitem_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='emoji',
            field=models.CharField(blank=True, default='📂', max_length=10),
        ),
    ]
