# Generated by Django 6.0.2 on 2026-02-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0006_categoria_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='is_sistema',
            field=models.BooleanField(default=False, help_text='Categoria do sistema, não pode ser editada ou excluída'),
        ),
    ]
